"""Tnitail migratiom

Revision ID: 6583a8fac506
Revises: 
Create Date: 2021-03-07 01:29:26.849951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6583a8fac506'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('postid', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['userid'])
    op.drop_column('post', 'id')
    op.add_column('user', sa.Column('userid', sa.Integer(), nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('user', 'userid')
    op.add_column('post', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'postid')
    # ### end Alembic commands ###
